# Granite 1340
Random Text.

[Granite 1340 Costs Tabel]
| PART       | Part Num  |  Price |     
| :--------: | :-------: -------: |
| Granite 1340 |  | $4039  |
|DRO Mounting kit       |K99-925  | $170.00 |
|3 axis DRO | 81-020 | $750.00 |
|Stand         |  | $339  |
 **Total** | |  |      |

