# What I Have Done To Date.

1. Set up GitHub.
2. Written installer program that self updates.
3. Modified act so that it ignores whitespace.
4. Updated dig commands so that they do not hang on sand and gravel.

# Next Steps.

1. Write program "run" that will execute a script from a file.
2. Add ability to ignore white space and carriage returns to run. 
3. Will have to investigate feasibility of using "\\" in turtle terminal to write longer scripts
4. Add line comments. I will use the Lua form "--".
4. Add block comments. Again I will use the Lua forms "---[[" and "--]]".

# Next Big Step

1. Add macros. These can be used not only for reusable pieces of code but since I will be using Lua tables the same mechanism can be used as variables.
2. Add ability to call code from an external file. The question is what should the syntax for calling from a separate file. One possibility is just to have a single file with all of the callable macros in it that is read by default by the "run" program and and can be read with a switch by the "do" program.
2. Add a more flexible looping mechanism with conditionals.
3. Add expressions.
4. A more robust inspect command. This could allow a simple inventory management with turtles. 

# The Big Goals Are:
1. Resource acquisition. Yes, they will be able to autonomously shaft mine the world effectively harvesting every useful block in those chunks. 
1. Inventory management with turtles. They will autonomously keep everything sorted and processed. 
2. Crafting. Give them minimum levels of items to maintain and they will craft as necessary. They will even call the miners for more raw materials. 
2. Construction. They will build everything from a shack to the Taj Mahal. From domed cities to fusion reactors.